/* CREACIÓN DE LAS TABLAS DE LA BASE DE DATOS */
CREATE TABLE Alumnos (
    MATRICULA VARCHAR ( 10 ) PRIMARY KEY,
    NOMBRE VARCHAR ( 30 ) NOT NULL,
    APELLIDOS VARCHAR ( 50 ) NOT NULL,
    EDAD INTEGER,
    PROMEDIO REAL
);

CREATE TABLE Materias (
    IDMATERIA VARCHAR ( 10 ) PRIMARY KEY,
    MATERIA VARCHAR ( 50 ) NOT NULL,
    CREDITOS INTEGER
);

CREATE TABLE Kardex (
    IDCALIFIC INTEGER PRIMARY KEY,
    MATRICULA VARCHAR ( 10 ),
    IDMATERIA VARCHAR ( 10 ) ,
    PERIODO VARCHAR ( 5 ),
    CALIFICACION INTEGER
);


/* CREACIÓN DE LLAVES FORANEAS PARA LA INTEGRIDAD REFERENCIAL                 */

ALTER TABLE Kardex ADD CONSTRAINT fk_matricula 
    FOREIGN KEY ( MATRICULA ) REFERENCES Alumnos ( MATRICULA );

ALTER TABLE Kardex ADD CONSTRAINT fk_idmateria 
    FOREIGN KEY ( IDMATERIA ) REFERENCES Materias ( IDMATERIA );

