/*------------------------------------------------------------------------------------------
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: ENE-JUN/2020    HORA: 17-18 HRS
:*
:*                               Clase DatosPrismaTriangular 
:*        
:*  Archivo     : DatosPrismaTriangular.java
:*  Autor       : Félix Gerardo Martínez Hinojo 17130800
:*  Fecha       : 26/NOV/2020
:*  Compilador  : JAVA J2SE v1.8.0
:*  Descripcion : Esta clase se encarga de la vista para añadir los datos de un prisma triangular , así como mandarla al bean y al frame que hace uso
:*              de ese bean en cuestión, el cual es jPrismaTriangular.
:*                
:*  Ultima modif: 
:*  Fecha       Modific�             Motivo
:*========================================================================================== 
:*  26/NOV/2020 Félix Mtz           Agregar prologo.
:*------------------------------------------------------------------------------------------*/
package mx.tecnm.itl.beans;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author FélixMtz
 */
public class DatosPrismaTriangular extends javax.swing.JDialog {

    private jPrismaTriangular parent;
    
    public DatosPrismaTriangular( jPrismaTriangular parent, boolean modal ) {
        super ( new Frame(), modal);
        initComponents();
        
        // conservamos la referencia a la vista
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLargo = new javax.swing.JLabel();
        jtxfC1 = new javax.swing.JTextField();
        jLabelAncho = new javax.swing.JLabel();
        jtxfC2 = new javax.swing.JTextField();
        jLabelAlto = new javax.swing.JLabel();
        jtxfAltura = new javax.swing.JTextField();
        jbtnCapturar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Capturar Datos Prisma Triangular");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelLargo.setText("Cateto 1");

        jLabelAncho.setText("Cateto 2");

        jLabelAlto.setText("Altura ( h )");

        jbtnCapturar.setText("Aceptar");
        jbtnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapturarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelAncho)
                                .addComponent(jLabelLargo))
                            .addComponent(jLabelAlto))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxfC1)
                            .addComponent(jtxfC2)
                            .addComponent(jtxfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbtnCapturar)
                        .addGap(77, 77, 77)
                        .addComponent(jbtnCancelar)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLargo)
                    .addComponent(jtxfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAncho)
                    .addComponent(jtxfC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlto)
                    .addComponent(jtxfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCapturar)
                    .addComponent(jbtnCancelar))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapturarActionPerformed
        double cateto1, cateto2, alto;
        
        // Convertimos a númerico el valor del Largo.
        try {
            cateto1 = Double.parseDouble ( jtxfC1.getText() );
        } catch ( NumberFormatException e) {
            JOptionPane.showMessageDialog (
                    this,
                    "Debe capturar un valor númerico para el Radio",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
            jtxfC1.requestFocus ();
            return;
        }
        
        // Convertimos a númerico el valor del Ancho.
        try {
            cateto2 = Double.parseDouble ( jtxfC2.getText() );
        } catch ( NumberFormatException e) {
            JOptionPane.showMessageDialog (
                    this,
                    "Debe capturar un valor númerico para el Radio",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
            jtxfC2.requestFocus ();
            return;
        }
        
        try {
            alto = Double.parseDouble ( jtxfAltura.getText() );
        } catch ( NumberFormatException e) {
            JOptionPane.showMessageDialog (
                    this,
                    "Debe capturar un valor númerico para el Radio",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
            jtxfAltura.requestFocus ();
            return;
        }
        
        // Creamos el EventObject que servirá para modificar el evento datosModificados
        DatosModificadosEvent ev = new DatosModificadosEvent ( parent.getC1(), parent.getC2(), parent.getAlto(), cateto1, cateto2, alto );
        
        
        // Establecer el cateto1, cateto2 y altura capturados en la vista y el modelo.
        parent.setC1 ( cateto1 );
        parent.setC2 ( cateto2 );
        parent.setAlto ( alto );
        setVisible ( false );
        
        // disparar el evento DatosModificados
        parent.fireDatosModificadosEvent ( ev );
        
    }//GEN-LAST:event_jbtnCapturarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.setVisible ( false );
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jtxfC1.setText ( parent.getC1 ()+ "" );
        jtxfC2.setText ( parent.getC2 ()+ "" );
        jtxfAltura.setText ( parent.getAlto ()+ "" );
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DatosPrismaTriangular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DatosPrismaTriangular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DatosPrismaTriangular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DatosPrismaTriangular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DatosPrismaTriangular dialog = new DatosPrismaTriangular(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlto;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelLargo;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCapturar;
    private javax.swing.JTextField jtxfAltura;
    private javax.swing.JTextField jtxfC1;
    private javax.swing.JTextField jtxfC2;
    // End of variables declaration//GEN-END:variables
}
