/*------------------------------------------------------------------------------------------
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: ENE-JUN/2020    HORA: 17-18 HRS
:*
:*                               Clase JCilindro 
:*        
:*  Archivo     : JCilindro.java
:*  Autor       : Félix Gerardo Martínez Hinojo 17130800
:*  Fecha       : 26/NOV/2020
:*  Compilador  : JAVA J2SE v1.8.0
:*  Descripcion : Esta Panel JCilindro sirve como bean para añadir a diferentes frames reutilizando código y vista.
:*                  especificamente de un Cilindro.
:*                
:*  Ultima modif: 
:*  Fecha       Modific�             Motivo
:*========================================================================================== 
:*  26/NOV/2020 Félix Mtz           Agregar prologo.
:*------------------------------------------------------------------------------------------*/

package mx.tecnm.itl.beans;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import mx.tecnm.itl.prismas.Cilindro;
import mx.tecnm.itl.prismas.IPrisma;
import mx.tecnm.itl.util.Imagenes;

public class JCilindro extends javax.swing.JPanel implements IPrisma {

    // Composición del BEAN.
    private Cilindro modelo;
    private DatosCilindroDialog datosCilDialog;
    private ArrayList<DatosModificadosListener> listener = new ArrayList<>();
    
    public JCilindro () {
        initComponents ();
        
        modelo = new Cilindro ();
        
        // Creamos el dialogo para los datos
        datosCilDialog = new DatosCilindroDialog ( this , true );
        
        // Ajustamos el tamaño de la imagen del prisma.
        Icon icon = jlblCilindro.getIcon ();
        icon = Imagenes.escalarImagen (
                icon,
                136,
                188
        );
        jlblCilindro.setIcon ( icon );
    }
    
    public JCilindro ( double radio, double altura ) {
        this(); // Invoca al constructor default de Cilindro de nuestro bean.
        
        modelo = new Cilindro ( radio, altura );
    }
    
    // Eventos del listener.
    public void addDatosModificadosListener ( DatosModificadosListener listener ) {
        this.listener.add ( listener );
    }
    
    public void removeDatosModificadosListener ( DatosModificadosListener listener ) {
        this.listener.remove ( listener );
    }
    
    public void fireDatosModificadosEvent ( DatosModificadosEvent ev ) {
        
        for ( DatosModificadosListener dModifListener : listener ) {
            dModifListener.datosModificadosPrisma ( ev );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopMenuDatos = new javax.swing.JPopupMenu();
        jmi_ValoresPrisma = new javax.swing.JMenuItem();
        jmi_AcercaDe = new javax.swing.JMenuItem();
        jlblCilindro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblRadio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblAltura = new javax.swing.JLabel();

        jmi_ValoresPrisma.setText("Valores del prisma");
        jmi_ValoresPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ValoresPrismaActionPerformed(evt);
            }
        });
        jPopMenuDatos.add(jmi_ValoresPrisma);

        jmi_AcercaDe.setText("Acerca De...");
        jmi_AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AcercaDeActionPerformed(evt);
            }
        });
        jPopMenuDatos.add(jmi_AcercaDe);

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setToolTipText("Use click derecho para acceder a mas opciones");
        setComponentPopupMenu(jPopMenuDatos);

        jlblCilindro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Cilindro.PNG"))); // NOI18N
        jlblCilindro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Radio ( r )");

        jlblRadio.setText("0");
        jlblRadio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblRadio.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel3.setText("Altura ( h )");

        jlblAltura.setText("0");
        jlblAltura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblAltura.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jlblRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AcercaDeActionPerformed
        JOptionPane.showMessageDialog (
                this,
                "JCilindro \n"+
                "V1.0 \n\n" +
                "TecNM Campus La Laguna\n\n"+
                "(C) Derechos reservados 2020",
                "Acerca De",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jmi_AcercaDeActionPerformed

    private void jmi_ValoresPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ValoresPrismaActionPerformed
        datosCilDialog.setVisible ( true );
    }//GEN-LAST:event_jmi_ValoresPrismaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopMenuDatos;
    private javax.swing.JLabel jlblAltura;
    private javax.swing.JLabel jlblCilindro;
    private javax.swing.JLabel jlblRadio;
    private javax.swing.JMenuItem jmi_AcercaDe;
    private javax.swing.JMenuItem jmi_ValoresPrisma;
    // End of variables declaration//GEN-END:variables

    @Override
    public double areaBase () {
        return modelo.areaBase ();
    }

    @Override
    public double areaLateral () {
        return modelo.areaLateral ();
    }

    @Override
    public double areaTotal () {
        return modelo.areaTotal ();
    }

    @Override
    public double volumen () {
        return modelo.volumen ();
    }
    
    // getters y setters
    public double getRadio () {
        return modelo.getRadio ();
    }
    
    public void setRadio ( double radio ) {
        modelo.setRadio ( radio );
        jlblRadio.setText ( radio + "" );
    }
    
    public double getAltura () {
        return modelo.getAltura ();
    }
    
    public void setAltura ( double altura ) {
        modelo.setAltura ( altura );
        jlblAltura.setText ( altura + "" );
    }
    
    
    
    
    
}
