/*------------------------------------------------------------------------------------------
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: ENE-JUN/2020    HORA: 17-18 HRS
:*
:*                               Clase JPrismaRectangular 
:*        
:*  Archivo     : JPrismaRectangular.java
:*  Autor       : Félix Gerardo Martínez Hinojo 17130800
:*  Fecha       : 26/NOV/2020
:*  Compilador  : JAVA J2SE v1.8.0
:*  Descripcion : Bean que tiene toda la vista necesaria para calcular y gestionar un Prisma Rectangular.
:*                
:*  Ultima modif: 
:*  Fecha       Modific�             Motivo
:*========================================================================================== 
:*  26/NOV/2020 Félix Mtz           Agregar prologo.
:*------------------------------------------------------------------------------------------*/
package mx.tecnm.itl.beans;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import mx.tecnm.itl.prismas.IPrisma;
import mx.tecnm.itl.prismas.PrismaRectangular;
import mx.tecnm.itl.util.Imagenes;


public class JPrismaRectangular extends javax.swing.JPanel implements IPrisma {

    // Composición del BEAN.
    private PrismaRectangular modelo;
    private DatosPrismaRectangular datosPRDialog;
    private ArrayList<DatosModificadosListener> listener = new ArrayList<>();
    
    public JPrismaRectangular () {
        initComponents();
        
        modelo = new PrismaRectangular ();
        
        // Creamos el dialogo para los datos
        datosPRDialog = new DatosPrismaRectangular ( this , true );
    
        // Ajustamos el tamaño de la imagen del prisma.
        Icon icon = jlblPR.getIcon ();
        icon = Imagenes.escalarImagen (
                icon,
                136,
                188
        );
        jlblPR.setIcon ( icon );
    }
    
    public JPrismaRectangular ( double largo, double ancho, double alto ) {
        this(); // Invoca al constructor default de Cilindro de nuestro bean.
        
        modelo = new PrismaRectangular ( largo, ancho, alto );
    }
    
    // Eventos del listener.
    public void addDatosModificadosListener ( DatosModificadosListener listener ) {
        this.listener.add ( listener );
    }
    
    public void removeDatosModificadosListener ( DatosModificadosListener listener ) {
        this.listener.remove ( listener );
    }
    
    public void fireDatosModificadosEvent ( DatosModificadosEvent ev ) {
        
        for ( DatosModificadosListener dModifListener : listener ) {
            dModifListener.datosModificadosPrisma ( ev );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpm_Datos = new javax.swing.JPopupMenu();
        jmi_Capturar = new javax.swing.JMenuItem();
        jmi_AcercaDe = new javax.swing.JMenuItem();
        jlblPR = new javax.swing.JLabel();
        jlblAncho = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblLargo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblAlto = new javax.swing.JLabel();

        jmi_Capturar.setText("Valores del prisma");
        jmi_Capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CapturarActionPerformed(evt);
            }
        });
        jpm_Datos.add(jmi_Capturar);

        jmi_AcercaDe.setText("AcercaDe");
        jmi_AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AcercaDeActionPerformed(evt);
            }
        });
        jpm_Datos.add(jmi_AcercaDe);

        setComponentPopupMenu(jpm_Datos);

        jlblPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/PrismaRectangular.jpg"))); // NOI18N
        jlblPR.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblAncho.setText("0");
        jlblAncho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblAncho.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel3.setText("Ancho");

        jlblLargo.setText("0");
        jlblLargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblLargo.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel2.setText("Largo");

        jLabel4.setText("Alto");

        jlblAlto.setText("0");
        jlblAlto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblAlto.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPR, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblPR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlblAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlblAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_CapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CapturarActionPerformed
        datosPRDialog.setVisible ( true );
    }//GEN-LAST:event_jmi_CapturarActionPerformed

    private void jmi_AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AcercaDeActionPerformed
        JOptionPane.showMessageDialog (
                this,
                "JCilindro \n"+
                "V1.0 \n\n" +
                "TecNM Campus La Laguna\n\n"+
                "(C) Derechos reservados 2020",
                "Acerca De",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jmi_AcercaDeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlblAlto;
    private javax.swing.JLabel jlblAncho;
    private javax.swing.JLabel jlblLargo;
    private javax.swing.JLabel jlblPR;
    private javax.swing.JMenuItem jmi_AcercaDe;
    private javax.swing.JMenuItem jmi_Capturar;
    private javax.swing.JPopupMenu jpm_Datos;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public double areaBase () {
        return modelo.areaBase ();
    }

    @Override
    public double areaLateral () {
        return modelo.areaLateral ();
    }

    @Override
    public double areaTotal () {
        return modelo.areaTotal ();
    }

    @Override
    public double volumen () {
        return modelo.volumen ();
    }
    
    // getters y setters
    
    public double getLargo () {
        return modelo.getLargo();
    }
    
    public void setLargo ( double largo ) {
        modelo.setLargo( largo );
        jlblLargo.setText ( largo + "" );
    }
    
    public double getAncho () {
        return modelo.getAncho();
    }
    
    public void setAncho ( double ancho ) {
        modelo.setAncho ( ancho );
        jlblAncho.setText ( ancho + "" );
    }
    
    public double getAlto () {
        return modelo.getAltura();
    }
    
    public void setAlto ( double altura ) {
        modelo.setAltura ( altura );
        jlblAlto.setText ( altura + "" );
    }
    
}
