/*------------------------------------------------------------------------------------------
:*                         TECNOLOGICO NACIONAL DE MEXICO
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: AGO-DIC/2020    HORA: 17-18 HRS
:*
:*                       Dialogo que permite añadir y Editar información referente a las Materias.
:*        
:*  Archivo     : Modulo2EditarDialog.java
:*  Autor       : Félix Gerardo Martínez Hinojo     17130800
:*  Fecha       : 01/DIC/2020
:*  Compilador  : JAVA J2SE v1.8.0
:*  Descripci�n : Dialogo que permite manejar la información de las Materias, tales como:
:*                
                    - ID Materia
                    - Materia
                    - Creditos
                  a traves de su clase pertinente.
:*  Ultima modif:
:*  Fecha       Modific�             Motivo
:*========================================================================================== 
:*  11/DIC/2020 Félix Mtz       Se añadió el dialog al proyecto y se le dió la definición básica..
    11/DIC/2020 Félix Mtz       Se añadieron los metodos pertinentes para acceder a la información.
    14/DIC/2020 Félix Mtz       Se corrigieron errores que evitaban que se añadiera información, como un valor no actualizado.
:*------------------------------------------------------------------------------------------*/
package app;

import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import modelo.Modelo1;
import modelo.Modelo2;
import mx.tecnm.itl.jdbc.EjecutorSQL;

public class Modulo2EditarDialog extends javax.swing.JDialog {

    private PrincipalFrame      frmPrincipal;
    private Modelo2             modelo;
    private String              accion;
    private Vector<String>      vecTiposColumnas;
    private String              sql;
    
    // ---------------------------------------------------------------------------------
    public Modulo2EditarDialog(java.awt.Frame parent, Modelo2 modelo ) {
        super(parent, true );
        initComponents();
        
        frmPrincipal        = ( PrincipalFrame ) parent;
        this.modelo         = modelo;
        vecTiposColumnas    = frmPrincipal.getVecTiposColumnas ();
        
//        accion = ( modelo == null ) ? PrincipalFrame.NUEVO : PrincipalFrame.EDITAR;
        if ( modelo == null )
            accion = PrincipalFrame.NUEVO;
        else
            accion = PrincipalFrame.EDITAR;
        
        setTitle ( accion );
        
        inicializarFormulario ();
    }
    
    // ---------------------------------------------------------------------------------

    private void inicializarFormulario () {
        if ( accion.equals ( PrincipalFrame.NUEVO ) ) {
            jtxfIDMateria.requestFocus ();
        } else if ( accion.equals ( PrincipalFrame.EDITAR ) ) {
            jtxfIDMateria.setText       ( modelo.getIdmateria   () );
            jtxfMateria.setText         ( modelo.getMateria     () );
            jtxfCreditos.setText        ( modelo.getCreditos    () + "" );
            
            jtxfMateria.requestFocus     ();
            jtxfIDMateria.setEditable   ( false );
        }
    }
    // ---------------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxfIDMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxfMateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxfCreditos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtnCancelar = new javax.swing.JButton();
        jbtnGuardar_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Materia:");

        jLabel2.setText("Materia:");

        jLabel3.setText("Creditos:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Student_96px.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnGuardar_.setText("Guardar");
        jbtnGuardar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jbtnGuardar_)
                .addGap(129, 129, 129)
                .addComponent(jbtnCancelar)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxfMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfIDMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxfIDMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxfMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxfCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnGuardar_))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // ---------------------------------------------------------------------------------
    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        dispose ();
    }//GEN-LAST:event_jbtnCancelarActionPerformed
    // ---------------------------------------------------------------------------------
    private void jbtnGuardar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardar_ActionPerformed
        Object[][] args =   null;
        String mensaje  =   "";

        if ( validarDatos () == false )
        return;

        // Se determina cual sentencia SQL se utilizará y se forma la matriz de argumentos
        if ( accion.equals ( PrincipalFrame.NUEVO ) ) {
            mensaje = "El registro ha sido agregado.";
            sql = frmPrincipal.getPropConsultasSQL().getProperty ( PrincipalFrame.MATERIAS_INSERTA_NUEVO );

            args = new Object[][] {
                { vecTiposColumnas.elementAt ( 0 ), modelo.getIdmateria     () },
                { vecTiposColumnas.elementAt ( 1 ), modelo.getMateria       () },
                { vecTiposColumnas.elementAt ( 2 ), modelo.getCreditos      () }
            };
        } else if ( accion.equals ( PrincipalFrame.EDITAR ) ) {
            mensaje = "El registro ha sido modificado.";
            sql = frmPrincipal.getPropConsultasSQL().getProperty ( PrincipalFrame.MATERIAS_ACTUALIZA_DATOS );
            args = new Object [][] {
                { vecTiposColumnas.elementAt ( 1 ), modelo.getMateria           () },
                { vecTiposColumnas.elementAt ( 2 ), modelo.getCreditos          () },
                { vecTiposColumnas.elementAt ( 0 ), modelo.getIdmateria         () }
            };
        }

        try {
            int regs = EjecutorSQL.sqlEjecutar ( sql, args );
            if ( regs == 1 ) {
                frmPrincipal.getJbtnModulo2().doClick ();
                JOptionPane.showMessageDialog( this,
                    mensaje,
                    accion,
                    JOptionPane.INFORMATION_MESSAGE );
            }
        } catch ( SQLException ex ) {
            dialogoMensaje ( ex.toString () );
        }

        dispose ();
    }//GEN-LAST:event_jbtnGuardar_ActionPerformed
    // ---------------------------------------------------------------------------------
    private boolean validarDatos () {
        String idmateria = jtxfIDMateria.getText ();
        if ( idmateria.trim().equals ( "" ) ) {
            dialogoMensaje ( "No se permite un valor en blanco" );
            jtxfIDMateria.requestFocus ();
            return false;
        }
        
        String materia = jtxfMateria.getText ();
        if ( materia.trim().equals ( "" ) ) {
            dialogoMensaje ( "No se permite un valor en blanco" );
            jtxfMateria.requestFocus ();
            return false;
        }
        
        int creditos;
        try {
            creditos = Integer.parseInt ( jtxfCreditos.getText () ); 
        } catch ( NumberFormatException e) {
            dialogoMensaje ( "Debe capturar un valor númerico válido" );
            jtxfCreditos.requestFocus ();
            return false;
        }
        
        modelo = new Modelo2 ( idmateria, materia, creditos );
        return true;
    }
    // ---------------------------------------------------------------------------------
    private void dialogoMensaje ( String mensaje ) {
        JOptionPane.showMessageDialog( this, mensaje, "Error", JOptionPane.ERROR_MESSAGE );
    }
    // ---------------------------------------------------------------------------------
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo2EditarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo2EditarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo2EditarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo2EditarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modulo2EditarDialog dialog = new Modulo2EditarDialog(new javax.swing.JFrame(), null );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnGuardar_;
    private javax.swing.JTextField jtxfCreditos;
    private javax.swing.JTextField jtxfIDMateria;
    private javax.swing.JTextField jtxfMateria;
    // End of variables declaration//GEN-END:variables
}
